language: node_js
node_js:
  - "7"
before_script:
  - npm run lernahoist
  # - npm run testdevenv
# the npm package `sharp` affects this file in the lines marked !*%*!
addons:
  apt:
    sources:
    # !*%*!
    - ubuntu-toolchain-r-test
    packages:
    # !*%*!
    - g++-4.8
env:
  global:
    # !*%*!
    - CXX=g++-4.8
    # bash command `mktemp` is used somewhere, and travis needs this line
    - TMPDIR=/tmp